### ISSUE TITLE
Support stars in imports besides trailing slashes

### ISSUE THREAD

**Issue by daKmoR** [WICG/import-maps#284] opened 2022-08-01 14:44 UTC
Currently, import maps have a trailing slash functionality that allows importing anything within a folder

```json
{
  "imports": {
    "moment": "/node_modules/moment/src/moment.js",
    "moment/": "/node_modules/moment/src/"
  }
}
```

e.g. the above would allow imports like

```js
import absCeil from 'moment/lib/utils/abs-ceil.js';
import indexOf from 'moment/lib/utils/index-of.js';
```

to work. [see moment src to verify](https://unpkg.com/browse/moment@2.29.4/src/lib/utils/)

## Issue

1. The trailing slash functionality feels "magical" in that unless you know it there is a low chance you would guess that behavior.
2. It behaves differently than node entry point exports
3. Trailing slash imports allow every file to be imported e.g. also potentially not intended imports like
   ```js
   import privateJson from 'moment/lib/private.json' assert { type: 'json' };
   ```

## Suggestion

Besides the trailing slash functionality also support `*` as a "simple string replace" functionality.
e.g. the above could then also be written as

```json
{
  "imports": {
    "moment": "/node_modules/moment/src/moment.js",
    "moment/*": "/node_modules/moment/src/*"
  }
}
```

this fixes 
1. as it is more obvious that it supports `*` after "moment".
2. as it can be 1:1 mapped to how node entry points work (which enables tools to very simply generate an import maps out of exports)

   ```json
   "exports": {
     "./*": "./src/*",
   }
   ```
   Note: trailing slash exports have been deprecated with node 16 and have been removed since node 17 (iirc)
   
The import would remain exactly the same

```js
import absCeil from 'moment/lib/utils/abs-ceil.js';
import indexOf from 'moment/lib/utils/index-of.js';
```

as the `*` will be replaced with `lib/utils/abs-ceil.js` in `"/node_modules/moment/src/*"`. 
Resulting in an actual import of `/node_modules/moment/src/lib/utils/abs-ceil.js`.

Note: potentially in a first iteration we could only support `*` at the end of a `/` (e.g. functional `foo/*` would be the same as `foo/`)

## Support limitations and extensionless imports

In node the star `*` can not only be at the end of the import but also before a file extension.

e.g. the following exports

```json
"exports": {
  "./*.js": "./src/*.js",
}
```

The import would change to extensionless but the actual file would remain the same

```js
import absCeil from 'moment/lib/utils/abs-ceil';
import indexOf from 'moment/lib/utils/index-of';
```

as the `*` will be replaced with `lib/utils/abs-ceil` in `"/node_modules/moment/src/*.js"`. 
Resulting in an actual import of `/node_modules/moment/src/lib/utils/abs-ceil.js`.

This solves our last remaining issue (Nr. 3) by limiting what can be imported to only `.js` files.

To quote nodes docs about the implementation
> `*` maps expose nested subpaths as it is a string replacement syntax only.

https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#packages_subpath_patterns

What do you think? should `*` be supported in an import-map?

**Comment by domenic** [comment] 2022-08-02 02:47
Dupe of #7 and its various duplicates.

**Closed by domenic** 2022-08-02 02:47 UTC
